[package]
name = "proc-macros"
edition = "2021"
license = "MIT"
version.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.46"
syn = "1.0.102"
